import { DatabaseSync } from "node:sqlite";
import type { InsertType, SelectType } from "kysely";
import { describe, expect, expectTypeOf, test } from "vitest";
import { SCHEMA } from "./schema.gen";
import { introspectSchema } from "./schema-introspection";
import type { DB } from "./tables";

describe("SCHEMA", () => {
	test("matches the migrated database (run `pnpm run schema:generate` after a migration)", () => {
		const database = new DatabaseSync("db-test.sqlite3", { readOnly: true });
		try {
			expect(JSON.parse(JSON.stringify(SCHEMA))).toEqual(
				introspectSchema(database),
			);
		} finally {
			database.close();
		}
	});

	test("matches the tables, columns, nullability and defaults of tables.ts", () => {
		expectTypeOf<TablesDrift>().toEqualTypeOf<never>();
	});
});

type Schema = typeof SCHEMA;
type Metadata<T extends keyof Schema> = Schema[T];

type TablesDrift =
	| `${Exclude<keyof DB & string, keyof Schema>} is not in the database`
	| `${Exclude<keyof Schema & string, keyof DB>} is missing from tables.ts`
	| {
			[T in keyof DB & keyof Schema & string]: ColumnDrift<T>;
	  }[keyof DB & keyof Schema & string];

type ColumnDrift<T extends keyof DB & keyof Schema & string> =
	| `${T}.${Exclude<keyof DB[T] & string, Metadata<T>["columns"][number] | "rowid">} is not in the database`
	| `${T}.${Exclude<Metadata<T>["columns"][number], keyof DB[T]>} is missing from tables.ts`
	| (Metadata<T>["kind"] extends "table"
			? {
					[C in keyof DB[T] & Metadata<T>["columns"][number]]: ColumnTypeDrift<
						T,
						C
					>;
				}[keyof DB[T] & Metadata<T>["columns"][number]]
			: never);

type ColumnTypeDrift<
	T extends keyof DB & keyof Schema & string,
	C extends keyof DB[T] & string,
> =
	| ([null extends SelectType<DB[T][C]> ? true : false] extends [
			C extends Metadata<T>["nullable"][number] ? true : false,
	  ]
			? never
			: C extends Metadata<T>["generatedAlways"][number]
				? never
				: `${T}.${C} nullability differs`)
	| ([InsertKind<DB[T][C]>] extends [ExpectedInsertKind<T, C>]
			? never
			: `${T}.${C} should be ${ExpectedInsertKind<T, C>}`);

type InsertKind<Column> = [InsertType<Column>] extends [never]
	? "GeneratedAlways"
	: undefined extends InsertType<Column>
		? "Generated"
		: "required";

// an integer primary key is generated by SQLite unless the app supplies it (PlusTier.userId),
// and a nullable column without a default is optional on insert either way
type ExpectedInsertKind<
	T extends keyof DB & keyof Schema & string,
	C extends string,
> = C extends Metadata<T>["generatedAlways"][number]
	? "GeneratedAlways"
	: C extends Metadata<T>["withDefault"][number]
		? "Generated"
		: Metadata<T>["primaryKey"] extends readonly [C]
			? "GeneratedAlways" | "required"
			: C extends Metadata<T>["nullable"][number]
				? "Generated" | "required"
				: "required";
