import type * as MapPool from '$lib/core/maps/MapPool';
import { stagesObj as s } from './in-game/stage-ids';

export const BANNED_MAPS: MapPool.MapPool = {
	TW: [],
	SZ: [s.STURGEON_SHIPYARD, s.EELTAIL_ALLEY],
	TC: [
		s.WAHOO_WORLD,
		s.FLOUNDER_HEIGHTS,
		s.BRINEWATER_SPRINGS,
		s.SCORCH_GORGE,
		s.MAHI_MAHI_RESORT,
		s.MINCEMEAT_METALWORKS,
		s.HUMPBACK_PUMP_TRACK,
		s.BLUEFIN_DEPOT,
		s.CRABLEG_CAPITAL,
		s.MARLIN_AIRPORT,
		s.LEMURIA_HUB
	],
	RM: [
		s.EELTAIL_ALLEY,
		s.WAHOO_WORLD,
		s.BRINEWATER_SPRINGS,
		s.BLUEFIN_DEPOT,
		s.STURGEON_SHIPYARD,
		s.INKBLOT_ART_ACADEMY,
		s.SHIPSHAPE_CARGO_CO,
		s.MAHI_MAHI_RESORT,
		s.MARLIN_AIRPORT,
		s.HAMMERHEAD_BRIDGE,
		s.LEMURIA_HUB
	],
	CB: [
		s.HAMMERHEAD_BRIDGE,
		s.STURGEON_SHIPYARD,
		s.WAHOO_WORLD,
		s.FLOUNDER_HEIGHTS,
		s.MINCEMEAT_METALWORKS,
		s.EELTAIL_ALLEY,
		s.UNDERTOW_SPILLWAY,
		s.MAHI_MAHI_RESORT,
		s.BLUEFIN_DEPOT,
		s.MARLIN_AIRPORT,
		s.LEMURIA_HUB
	]
};
