/**
 * English weapon names keyed by in-game weapon id, generated from
 * sendou.ink locales/en/weapons.json (MAIN_/SUB_/SPECIAL_<id> entries;
 * mains filtered to the assets/cv/main-weapons icon manifest).
 * The death screen shows the killer's weapon as text ("Splatted by
 * <name>!") and can credit a main, sub, or special, so the closed set
 * that OCR output snaps to spans all three kinds. Ids are only unique
 * within a kind (sub 0 = Splat Bomb, main 0 = Sploosh-o-matic).
 */
export type WeaponType = "MAIN" | "SUB" | "SPECIAL";

export interface WeaponEntry {
	id: string;
	name: string;
	type: WeaponType;
}

const WEAPON_NAMES: ReadonlyMap<string, string> = new Map([
	["0", "Sploosh-o-matic"],
	["1", "Neo Sploosh-o-matic"],
	["10", "Splattershot Jr."],
	["11", "Custom Splattershot Jr."],
	["20", "Splash-o-matic"],
	["21", "Neo Splash-o-matic"],
	["22", "Splash-o-matic GCK-O"],
	["30", "Aerospray MG"],
	["31", "Aerospray RG"],
	["32", "Colorz Aerospray"],
	["40", "Splattershot"],
	["41", "Tentatek Splattershot"],
	["42", "Glamorz Splattershot"],
	["45", "Hero Shot Replica"],
	["46", "Octo Shot Replica"],
	["47", "Order Shot Replica"],
	["48", "Plastic-Bottle Shot Replica"],
	["50", ".52 Gal"],
	["51", ".52 Gal Deco"],
	["60", "N-ZAP '85"],
	["61", "N-ZAP '89"],
	["70", "Splattershot Pro"],
	["71", "Forge Splattershot Pro"],
	["72", "Splattershot Pro FRZ-N"],
	["80", ".96 Gal"],
	["81", ".96 Gal Deco"],
	["82", "Clawz .96 Gal"],
	["90", "Jet Squelcher"],
	["91", "Custom Jet Squelcher"],
	["92", "Jet Squelcher COB-R"],
	["100", "Splattershot Nova"],
	["101", "Annaki Splattershot Nova"],
	["200", "Luna Blaster"],
	["201", "Luna Blaster Neo"],
	["205", "Order Blaster Replica"],
	["210", "Blaster"],
	["211", "Custom Blaster"],
	["212", "Gleamz Blaster"],
	["220", "Range Blaster"],
	["221", "Custom Range Blaster"],
	["230", "Clash Blaster"],
	["231", "Clash Blaster Neo"],
	["240", "Rapid Blaster"],
	["241", "Rapid Blaster Deco"],
	["250", "Rapid Blaster Pro"],
	["251", "Rapid Blaster Pro Deco"],
	["252", "Rapid Blaster Pro WNT-R"],
	["260", "S-BLAST '92"],
	["261", "S-BLAST '91"],
	["300", "L-3 Nozzlenose"],
	["301", "L-3 Nozzlenose D"],
	["302", "Glitterz L-3 Nozzlenose"],
	["310", "H-3 Nozzlenose"],
	["311", "H-3 Nozzlenose D"],
	["312", "H-3 Nozzlenose VIP-R"],
	["400", "Squeezer"],
	["401", "Foil Squeezer"],
	["1000", "Carbon Roller"],
	["1001", "Carbon Roller Deco"],
	["1002", "Carbon Roller ANG-L"],
	["1010", "Splat Roller"],
	["1011", "Krak-On Splat Roller"],
	["1015", "Order Roller Replica"],
	["1020", "Dynamo Roller"],
	["1021", "Gold Dynamo Roller"],
	["1022", "Starz Dynamo Roller"],
	["1030", "Flingza Roller"],
	["1031", "Foil Flingza Roller"],
	["1040", "Big Swig Roller"],
	["1041", "Big Swig Roller Express"],
	["1042", "Planetz Big Swig Roller"],
	["1100", "Inkbrush"],
	["1101", "Inkbrush Nouveau"],
	["1110", "Octobrush"],
	["1111", "Octobrush Nouveau"],
	["1112", "Cometz Octobrush"],
	["1115", "Orderbrush Replica"],
	["1120", "Painbrush"],
	["1121", "Painbrush Nouveau"],
	["1122", "Painbrush BRN-Z"],
	["2000", "Classic Squiffer"],
	["2001", "New Squiffer"],
	["2010", "Splat Charger"],
	["2011", "Z+F Splat Charger"],
	["2012", "Splat Charger CAM-O"],
	["2015", "Order Charger Replica"],
	["2020", "Splatterscope"],
	["2021", "Z+F Splatterscope"],
	["2022", "Splatterscope CAM-O"],
	["2030", "E-liter 4K"],
	["2031", "Custom E-liter 4K"],
	["2040", "E-liter 4K Scope"],
	["2041", "Custom E-liter 4K Scope"],
	["2050", "Bamboozler 14 Mk I"],
	["2051", "Bamboozler 14 Mk II"],
	["2060", "Goo Tuber"],
	["2061", "Custom Goo Tuber"],
	["2070", "Snipewriter 5H"],
	["2071", "Snipewriter 5B"],
	["3000", "Slosher"],
	["3001", "Slosher Deco"],
	["3005", "Order Slosher Replica"],
	["3010", "Tri-Slosher"],
	["3011", "Tri-Slosher Nouveau"],
	["3012", "Tri-Slosher ASH-N"],
	["3020", "Sloshing Machine"],
	["3021", "Sloshing Machine Neo"],
	["3030", "Bloblobber"],
	["3031", "Bloblobber Deco"],
	["3040", "Explosher"],
	["3041", "Custom Explosher"],
	["3050", "Dread Wringer"],
	["3051", "Dread Wringer D"],
	["3052", "Hornz Dread Wringer"],
	["4000", "Mini Splatling"],
	["4001", "Zink Mini Splatling"],
	["4002", "Mini Splatling RTL-R"],
	["4010", "Heavy Splatling"],
	["4011", "Heavy Splatling Deco"],
	["4015", "Order Splatling Replica"],
	["4020", "Hydra Splatling"],
	["4021", "Custom Hydra Splatling"],
	["4022", "Torrentz Hydra Splatling"],
	["4030", "Ballpoint Splatling"],
	["4031", "Ballpoint Splatling Nouveau"],
	["4040", "Nautilus 47"],
	["4041", "Nautilus 79"],
	["4050", "Heavy Edit Splatling"],
	["4051", "Heavy Edit Splatling Nouveau"],
	["5000", "Dapple Dualies"],
	["5001", "Dapple Dualies Nouveau"],
	["5002", "Dapple Dualies NOC-T"],
	["5010", "Splat Dualies"],
	["5011", "Enperry Splat Dualies"],
	["5012", "Twinklez Splat Dualies"],
	["5015", "Order Dualie Replicas"],
	["5020", "Glooga Dualies"],
	["5021", "Glooga Dualies Deco"],
	["5030", "Dualie Squelchers"],
	["5031", "Custom Dualie Squelchers"],
	["5032", "Hoofz Dualie Squelchers"],
	["5040", "Dark Tetra Dualies"],
	["5041", "Light Tetra Dualies"],
	["5050", "Douser Dualies FF"],
	["5051", "Custom Douser Dualies FF"],
	["6000", "Splat Brella"],
	["6001", "Sorella Brella"],
	["6005", "Order Brella Replica"],
	["6010", "Tenta Brella"],
	["6011", "Tenta Sorella Brella"],
	["6012", "Tenta Brella CRE-M"],
	["6020", "Undercover Brella"],
	["6021", "Undercover Sorella Brella"],
	["6022", "Patternz Undercover Brella"],
	["6030", "Recycled Brella 24 Mk I"],
	["6031", "Recycled Brella 24 Mk II"],
	["7010", "Tri-Stringer"],
	["7011", "Inkline Tri-Stringer"],
	["7012", "Bulbz Tri-Stringer"],
	["7015", "Order Stringer Replica"],
	["7020", "REEF-LUX 450"],
	["7021", "REEF-LUX 450 Deco"],
	["7022", "REEF-LUX 450 MIL-K"],
	["7030", "Wellstring V"],
	["7031", "Custom Wellstring V"],
	["8000", "Splatana Stamper"],
	["8001", "Splatana Stamper Nouveau"],
	["8002", "Stickerz Splatana Stamper"],
	["8005", "Order Splatana Replica"],
	["8010", "Splatana Wiper"],
	["8011", "Splatana Wiper Deco"],
	["8012", "Splatana Wiper RUS-T"],
	["8020", "Mint Decavitator"],
	["8021", "Charcoal Decavitator"],
]);

const SUB_WEAPON_NAMES: ReadonlyMap<string, string> = new Map([
	["0", "Splat Bomb"],
	["1", "Suction Bomb"],
	["2", "Burst Bomb"],
	["3", "Sprinkler"],
	["4", "Splash Wall"],
	["5", "Fizzy Bomb"],
	["6", "Curling Bomb"],
	["7", "Autobomb"],
	["8", "Squid Beakon"],
	["9", "Point Sensor"],
	["10", "Ink Mine"],
	["11", "Toxic Mist"],
	["12", "Angle Shooter"],
	["13", "Torpedo"],
]);

const SPECIAL_WEAPON_NAMES: ReadonlyMap<string, string> = new Map([
	["1", "Trizooka"],
	["2", "Big Bubbler"],
	["3", "Zipcaster"],
	["4", "Tenta Missiles"],
	["5", "Ink Storm"],
	["6", "Booyah Bomb"],
	["7", "Wave Breaker"],
	["8", "Ink Vac"],
	["9", "Killer Wail 5.1"],
	["10", "Inkjet"],
	["11", "Ultra Stamp"],
	["12", "Crab Tank"],
	["13", "Reefslider"],
	["14", "Triple Inkstrike"],
	["15", "Tacticooler"],
	["16", "Super Chump"],
	["17", "Kraken Royale"],
	["18", "Triple Splashdown"],
	["19", "Splattercolor Screen"],
]);

function entriesOf(
	map: ReadonlyMap<string, string>,
	type: WeaponType,
): WeaponEntry[] {
	return [...map.entries()].map(([id, name]) => ({ id, name, type }));
}

/** Every weapon that can appear in the death message, across all kinds. */
export const ALL_WEAPON_ENTRIES: readonly WeaponEntry[] = [
	...entriesOf(WEAPON_NAMES, "MAIN"),
	...entriesOf(SUB_WEAPON_NAMES, "SUB"),
	...entriesOf(SPECIAL_WEAPON_NAMES, "SPECIAL"),
];
