export const TOURNAMENT_SERIES_EVENTS_PER_PAGE = 20;
export const TOURNAMENT_SERIES_LEADERBOARD_SIZE = 50;

export const MONTH_PARAM_FORMAT = "yyyy-MM";

export const ESTABLISHED_ORG = {
	MONTHS_CONSIDERED: 6,
	GAIN_THRESHOLD: 150,
	LOSE_THRESHOLD: 100,
};

export const TOURNAMENT_ORGANIZATION = {
	DESCRIPTION_MAX_LENGTH: 1_000,
	BAN_REASON_MAX_LENGTH: 200,
	MAX_BANNED_USERS: 100,
	MAX_MEMBER_OF_COUNT: 5,
};
