/**
 * GENERATED by scripts/scanner/build-localized-entries.ts from the splat3 repo's
 * language dumps — do not edit by hand; regenerate when the game adds
 * content. Localized versus-UI strings for every game language, each
 * mapped to the sendou.ink id it means (core/localized.ts derives the
 * flattened match sets detectors snap OCR output against).
 */
import type { ModeShort, StageId } from "~/modules/in-game-lists/types";
import type { ScannerLobby } from "../scanner-types";

export interface LocalizedLobby {
	text: string;
	lobby: ScannerLobby;
}

export interface LocalizedMode {
	text: string;
	mode: ModeShort;
}

export interface LocalizedStage {
	text: string;
	stageId: StageId;
}

export interface LanguageEntries {
	lang: string;
	/** the intro splash's constant "MODE" label */
	modeLabel: string;
	/** replay-browser winner/loser panel tags */
	victory: string;
	defeat: string;
	lobbies: LocalizedLobby[];
	modes: LocalizedMode[];
	/** two-line intro-splash wrap variants ("Muschel-\nchaos"), space-joined */
	modeWraps: LocalizedMode[];
	stages: LocalizedStage[];
}

export const LANGUAGE_ENTRIES: readonly LanguageEntries[] = [
	{
		lang: "CNzh",
		modeLabel: "规则",
		victory: "WIN！",
		defeat: "LOSE...",
		lobbies: [
			{
				text: "X比赛",
				lobby: "X",
			},
			{
				text: "蛮颓比赛（挑战）",
				lobby: "SERIES",
			},
			{
				text: "蛮颓比赛（开放）",
				lobby: "OPEN",
			},
			{
				text: "私人比赛",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "占地对战",
				mode: "TW",
			},
			{
				text: "真格区域",
				mode: "SZ",
			},
			{
				text: "真格塔楼",
				mode: "TC",
			},
			{
				text: "真格鱼虎对战",
				mode: "RM",
			},
			{
				text: "真格蛤蜊",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "龙宫转运站",
				stageId: 23,
			},
			{
				text: "臭鱼干温泉",
				stageId: 13,
			},
			{
				text: "醋饭海洋世界",
				stageId: 11,
			},
			{
				text: "十路通高架桥下",
				stageId: 24,
			},
			{
				text: "贝见亭",
				stageId: 21,
			},
			{
				text: "鳗鲶区",
				stageId: 1,
			},
			{
				text: "鱼露遗迹",
				stageId: 15,
			},
			{
				text: "鬼头刀SPA度假区",
				stageId: 7,
			},
			{
				text: "比目鱼住宅区",
				stageId: 12,
			},
			{
				text: "真鲭跨海大桥",
				stageId: 5,
			},
			{
				text: "座头购物中心",
				stageId: 10,
			},
			{
				text: "鲟鱼造船厂",
				stageId: 9,
			},
			{
				text: "鬼蝠鲼玛利亚号",
				stageId: 14,
			},
			{
				text: "金眼鲷美术馆",
				stageId: 6,
			},
			{
				text: "旗鱼机场",
				stageId: 22,
			},
			{
				text: "葱鲔鱼煤矿场",
				stageId: 20,
			},
			{
				text: "鱼肉碎金属",
				stageId: 4,
			},
			{
				text: "塔拉波特购物公园",
				stageId: 17,
			},
			{
				text: "高脚经济特区",
				stageId: 18,
			},
			{
				text: "竹蛏疏洪道",
				stageId: 3,
			},
			{
				text: "大比目鱼海运中心",
				stageId: 19,
			},
			{
				text: "海女美术大学",
				stageId: 8,
			},
			{
				text: "昆布赛道",
				stageId: 16,
			},
			{
				text: "烟管鱼市场",
				stageId: 2,
			},
			{
				text: "温泉花大峡谷",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUde",
		modeLabel: "Kampfart",
		victory: "Sieg!",
		defeat: "Verloren...",
		lobbies: [
			{
				text: "X-Kampf",
				lobby: "X",
			},
			{
				text: "Anarchie-Kampf (Serie)",
				lobby: "SERIES",
			},
			{
				text: "Anarchie-Kampf (Offen)",
				lobby: "OPEN",
			},
			{
				text: "Privater Kampf",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Revierkampf",
				mode: "TW",
			},
			{
				text: "Herrschaft",
				mode: "SZ",
			},
			{
				text: "Turm-Kommando",
				mode: "TC",
			},
			{
				text: "Operation Goldfisch",
				mode: "RM",
			},
			{
				text: "Muschelchaos",
				mode: "CB",
			},
		],
		modeWraps: [
			{
				text: "Revier- kampf",
				mode: "TW",
			},
			{
				text: "Muschel- chaos",
				mode: "CB",
			},
		],
		stages: [
			{
				text: "Bahnhof Lemuria",
				stageId: 23,
			},
			{
				text: "Kusaya-Quellen",
				stageId: 13,
			},
			{
				text: "Flunder-Funpark",
				stageId: 11,
			},
			{
				text: "Dekabahnstation",
				stageId: 24,
			},
			{
				text: "ROM & RAMen",
				stageId: 21,
			},
			{
				text: "Streifenaal-Straße",
				stageId: 1,
			},
			{
				text: "Um'ami-Ruinen",
				stageId: 15,
			},
			{
				text: "Mahi-Mahi-Resort",
				stageId: 7,
			},
			{
				text: "Schollensiedlung",
				stageId: 12,
			},
			{
				text: "Makrelenbrücke",
				stageId: 5,
			},
			{
				text: "Cetacea-Markt",
				stageId: 10,
			},
			{
				text: "Störwerft",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Pinakoithek",
				stageId: 6,
			},
			{
				text: "La Ola Airport",
				stageId: 22,
			},
			{
				text: "Blauflossen-Depot",
				stageId: 20,
			},
			{
				text: "Aalstahl-Metallwerk",
				stageId: 4,
			},
			{
				text: "Talerfisch & Pock",
				stageId: 17,
			},
			{
				text: "Seespinnen-Skyline",
				stageId: 18,
			},
			{
				text: "Schwertmuschel-Reservoir",
				stageId: 3,
			},
			{
				text: "Frachtschiff Schwerfisch",
				stageId: 19,
			},
			{
				text: "Perlmutt-Akademie",
				stageId: 8,
			},
			{
				text: "Buckelwal-Piste",
				stageId: 16,
			},
			{
				text: "Schnapperchen-Basar",
				stageId: 2,
			},
			{
				text: "Sengkluft",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUen",
		modeLabel: "Mode",
		victory: "VICTORY",
		defeat: "DEFEAT",
		lobbies: [
			{
				text: "X Battle",
				lobby: "X",
			},
			{
				text: "Anarchy Battle (Series)",
				lobby: "SERIES",
			},
			{
				text: "Anarchy Battle (Open)",
				lobby: "OPEN",
			},
			{
				text: "Private Battle",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Turf War",
				mode: "TW",
			},
			{
				text: "Splat Zones",
				mode: "SZ",
			},
			{
				text: "Tower Control",
				mode: "TC",
			},
			{
				text: "Rainmaker",
				mode: "RM",
			},
			{
				text: "Clam Blitz",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Lemuria Hub",
				stageId: 23,
			},
			{
				text: "Brinewater Springs",
				stageId: 13,
			},
			{
				text: "Wahoo World",
				stageId: 11,
			},
			{
				text: "Urchin Underpass",
				stageId: 24,
			},
			{
				text: "Robo ROM-en",
				stageId: 21,
			},
			{
				text: "Eeltail Alley",
				stageId: 1,
			},
			{
				text: "Um'ami Ruins",
				stageId: 15,
			},
			{
				text: "Mahi-Mahi Resort",
				stageId: 7,
			},
			{
				text: "Flounder Heights",
				stageId: 12,
			},
			{
				text: "Hammerhead Bridge",
				stageId: 5,
			},
			{
				text: "MakoMart",
				stageId: 10,
			},
			{
				text: "Sturgeon Shipyard",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Museum d'Alfonsino",
				stageId: 6,
			},
			{
				text: "Marlin Airport",
				stageId: 22,
			},
			{
				text: "Bluefin Depot",
				stageId: 20,
			},
			{
				text: "Mincemeat Metalworks",
				stageId: 4,
			},
			{
				text: "Barnacle & Dime",
				stageId: 17,
			},
			{
				text: "Crableg Capital",
				stageId: 18,
			},
			{
				text: "Undertow Spillway",
				stageId: 3,
			},
			{
				text: "Shipshape Cargo Co.",
				stageId: 19,
			},
			{
				text: "Inkblot Art Academy",
				stageId: 8,
			},
			{
				text: "Humpback Pump Track",
				stageId: 16,
			},
			{
				text: "Hagglefish Market",
				stageId: 2,
			},
			{
				text: "Scorch Gorge",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUes",
		modeLabel: "Estilo",
		victory: "¡Victoria!",
		defeat: "Derrota",
		lobbies: [
			{
				text: "Combate X",
				lobby: "X",
			},
			{
				text: "Combate caótico (formal)",
				lobby: "SERIES",
			},
			{
				text: "Combate caótico (informal)",
				lobby: "OPEN",
			},
			{
				text: "Combate privado",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Territorial",
				mode: "TW",
			},
			{
				text: "Pintazonas",
				mode: "SZ",
			},
			{
				text: "Torre",
				mode: "TC",
			},
			{
				text: "Pez dorado",
				mode: "RM",
			},
			{
				text: "Asalto almeja",
				mode: "CB",
			},
		],
		modeWraps: [
			{
				text: "Terri- torial",
				mode: "TW",
			},
			{
				text: "Pinta- zonas",
				mode: "SZ",
			},
		],
		stages: [
			{
				text: "Terminal Dragón",
				stageId: 23,
			},
			{
				text: "Balneario Aguasal",
				stageId: 13,
			},
			{
				text: "Pirañalandia",
				stageId: 11,
			},
			{
				text: "Parque Viaducto",
				stageId: 24,
			},
			{
				text: "Factoría RAMen",
				stageId: 21,
			},
			{
				text: "Callejones Crustáceo",
				stageId: 1,
			},
			{
				text: "Ruinas Ceviche",
				stageId: 15,
			},
			{
				text: "Spa Cala Bacalao",
				stageId: 7,
			},
			{
				text: "Complejo Medusa",
				stageId: 12,
			},
			{
				text: "Puente Salmón",
				stageId: 5,
			},
			{
				text: "Ultramarinos Orca",
				stageId: 10,
			},
			{
				text: "Astillero Beluga",
				stageId: 9,
			},
			{
				text: "Corbeta Corvina",
				stageId: 14,
			},
			{
				text: "Museo del Pargo",
				stageId: 6,
			},
			{
				text: "Aeropuerto Marlín",
				stageId: 22,
			},
			{
				text: "Mina costera",
				stageId: 20,
			},
			{
				text: "Desguace Mero",
				stageId: 4,
			},
			{
				text: "Centro Comercial Fletán",
				stageId: 17,
			},
			{
				text: "Distrito Rascalópodo",
				stageId: 18,
			},
			{
				text: "Cisterna Navajuela",
				stageId: 3,
			},
			{
				text: "Carguero Platija",
				stageId: 19,
			},
			{
				text: "Instituto Coralino",
				stageId: 8,
			},
			{
				text: "Tiburódromo",
				stageId: 16,
			},
			{
				text: "Mercado Lenguado",
				stageId: 2,
			},
			{
				text: "Desfiladero Fumarola",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUfr",
		modeLabel: "Mode",
		victory: "Victoire !",
		defeat: "Défaite...",
		lobbies: [
			{
				text: "Match X",
				lobby: "X",
			},
			{
				text: "Match anarchie (série)",
				lobby: "SERIES",
			},
			{
				text: "Match anarchie (ouvert)",
				lobby: "OPEN",
			},
			{
				text: "Match privé",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Guerre de territoire",
				mode: "TW",
			},
			{
				text: "Défense de zone",
				mode: "SZ",
			},
			{
				text: "Expédition risquée",
				mode: "TC",
			},
			{
				text: "Mission Bazookarpe",
				mode: "RM",
			},
			{
				text: "Pluie de palourdes",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Gare Aiguillat",
				stageId: 23,
			},
			{
				text: "Sources Sauret",
				stageId: 13,
			},
			{
				text: "Parc Carapince",
				stageId: 11,
			},
			{
				text: "Passage Turbot",
				stageId: 24,
			},
			{
				text: "Arène Méca-ramen",
				stageId: 21,
			},
			{
				text: "Banlieue Balibot",
				stageId: 1,
			},
			{
				text: "Ruines Uma'mi",
				stageId: 15,
			},
			{
				text: "Club Ca$halot",
				stageId: 7,
			},
			{
				text: "Lotissement Filament",
				stageId: 12,
			},
			{
				text: "Pont Esturgeon",
				stageId: 5,
			},
			{
				text: "Supermarché Cétacé",
				stageId: 10,
			},
			{
				text: "Chantier Narval",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Galeries Guppy",
				stageId: 6,
			},
			{
				text: "Terminal Rorqual",
				stageId: 22,
			},
			{
				text: "Mine marine",
				stageId: 20,
			},
			{
				text: "Casse Rascasse",
				stageId: 4,
			},
			{
				text: "Halles de Port-merlu",
				stageId: 17,
			},
			{
				text: "Quartier Crabe-ciels",
				stageId: 18,
			},
			{
				text: "Réservoir Rigadelle",
				stageId: 3,
			},
			{
				text: "Chaland Flétan",
				stageId: 19,
			},
			{
				text: "Institut Calam'arts",
				stageId: 8,
			},
			{
				text: "Piste Méroule",
				stageId: 16,
			},
			{
				text: "Marché Grefin",
				stageId: 2,
			},
			{
				text: "Canyon aux colonnes",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUit",
		modeLabel: "Modalità",
		victory: "Vittoria",
		defeat: "Sconfitta",
		lobbies: [
			{
				text: "Partita X",
				lobby: "X",
			},
			{
				text: "Partita anarchica (Serie)",
				lobby: "SERIES",
			},
			{
				text: "Partita anarchica (Aperta)",
				lobby: "OPEN",
			},
			{
				text: "Partita privata",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Mischia mollusca",
				mode: "TW",
			},
			{
				text: "Zona splat",
				mode: "SZ",
			},
			{
				text: "Torre mobile",
				mode: "TC",
			},
			{
				text: "Bazookarp",
				mode: "RM",
			},
			{
				text: "Vongol gol",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Stazione Lemuria",
				stageId: 23,
			},
			{
				text: "Fermenterme",
				stageId: 13,
			},
			{
				text: "Soglioland",
				stageId: 11,
			},
			{
				text: "Periferia urbana",
				stageId: 24,
			},
			{
				text: "Roboramen",
				stageId: 21,
			},
			{
				text: "Sobborgo Siluriano",
				stageId: 1,
			},
			{
				text: "Rovine Salsadipesce",
				stageId: 15,
			},
			{
				text: "Villanguilla",
				stageId: 7,
			},
			{
				text: "Cime Sogliolose",
				stageId: 12,
			},
			{
				text: "Ponte Sgombro",
				stageId: 5,
			},
			{
				text: "Mercatotano",
				stageId: 10,
			},
			{
				text: "Cantiere Pinnenere",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Museo di Cefalò",
				stageId: 6,
			},
			{
				text: "Aeroporto Ondabianca",
				stageId: 22,
			},
			{
				text: "Molo Mollusco",
				stageId: 20,
			},
			{
				text: "Discarica Tritatutto",
				stageId: 4,
			},
			{
				text: "Empolporio",
				stageId: 17,
			},
			{
				text: "Granchiacieli",
				stageId: 18,
			},
			{
				text: "Cisterna Cernia",
				stageId: 3,
			},
			{
				text: "Platessa Trasporti S.r.l.",
				stageId: 19,
			},
			{
				text: "Campus Hippocampus",
				stageId: 8,
			},
			{
				text: "Tintodromo Montecarpa",
				stageId: 16,
			},
			{
				text: "Mercato Fruttato",
				stageId: 2,
			},
			{
				text: "Grank Canyon",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUnl",
		modeLabel: "Vechtstijl",
		victory: "Gewonnen!",
		defeat: "Verloren...",
		lobbies: [
			{
				text: "X-gevecht",
				lobby: "X",
			},
			{
				text: "Chaosgevecht (sessie)",
				lobby: "SERIES",
			},
			{
				text: "Chaosgevecht (open)",
				lobby: "OPEN",
			},
			{
				text: "Privégevecht",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Grondoorlog",
				mode: "TW",
			},
			{
				text: "Spetterzone",
				mode: "SZ",
			},
			{
				text: "Torentwist",
				mode: "TC",
			},
			{
				text: "Bazookarper",
				mode: "RM",
			},
			{
				text: "Schelpenstrijd",
				mode: "CB",
			},
		],
		modeWraps: [
			{
				text: "Grond- oorlog",
				mode: "TW",
			},
			{
				text: "Spetter- zone",
				mode: "SZ",
			},
			{
				text: "Toren- twist",
				mode: "TC",
			},
			{
				text: "Bazoo- karper",
				mode: "RM",
			},
			{
				text: "Schelpen- strijd",
				mode: "CB",
			},
		],
		stages: [
			{
				text: "Lemurië Centraal",
				stageId: 23,
			},
			{
				text: "Barbeelbaden",
				stageId: 13,
			},
			{
				text: "Waterwonderland",
				stageId: 11,
			},
			{
				text: "Knooppunt Kabeljauw",
				stageId: 24,
			},
			{
				text: "Bami-Byte",
				stageId: 21,
			},
			{
				text: "Forelviaduct",
				stageId: 1,
			},
			{
				text: "Ruisvoornruïnes",
				stageId: 15,
			},
			{
				text: "El Dorade-resort",
				stageId: 7,
			},
			{
				text: "Baleinbuurt",
				stageId: 12,
			},
			{
				text: "Brandingbrug",
				stageId: 5,
			},
			{
				text: "Bultrugbazaar",
				stageId: 10,
			},
			{
				text: "Walruswerf",
				stageId: 9,
			},
			{
				text: "Klipvisklipper",
				stageId: 14,
			},
			{
				text: "Galerie Le Guppy",
				stageId: 6,
			},
			{
				text: "Trekvis Airport",
				stageId: 22,
			},
			{
				text: "Blauwvin-depot",
				stageId: 20,
			},
			{
				text: "Zilversmelt-hoogovens",
				stageId: 4,
			},
			{
				text: "Winkelcentrum Poon & Zeehaan",
				stageId: 17,
			},
			{
				text: "Visstickdistrict",
				stageId: 18,
			},
			{
				text: "Baarsreservoir",
				stageId: 3,
			},
			{
				text: "Tarbot Transport",
				stageId: 19,
			},
			{
				text: "Koraalcampus",
				stageId: 8,
			},
			{
				text: "Lekkerbektrack",
				stageId: 16,
			},
			{
				text: "Boter-bij-de-vismarkt",
				stageId: 2,
			},
			{
				text: "Roggentrog",
				stageId: 0,
			},
		],
	},
	{
		lang: "EUru",
		modeLabel: "Режим",
		victory: "Успех!",
		defeat: "Провал",
		lobbies: [
			{
				text: "Бой X",
				lobby: "X",
			},
			{
				text: "Стихийный бой (серия)",
				lobby: "SERIES",
			},
			{
				text: "Стихийный бой (открытый)",
				lobby: "OPEN",
			},
			{
				text: "Частный бой",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Бой за район",
				mode: "TW",
			},
			{
				text: "Бой за зоны",
				mode: "SZ",
			},
			{
				text: "Бой за башню",
				mode: "TC",
			},
			{
				text: "Мегакарп",
				mode: "RM",
			},
			{
				text: "Устробол",
				mode: "CB",
			},
		],
		modeWraps: [
			{
				text: "Устро- бол",
				mode: "CB",
			},
		],
		stages: [
			{
				text: "Вокзал Лемурия",
				stageId: 23,
			},
			{
				text: "Тухловодск",
				stageId: 13,
			},
			{
				text: "Луна-парк «Язь»",
				stageId: 11,
			},
			{
				text: "Район Дека",
				stageId: 24,
			},
			{
				text: "«Роборамэн»",
				stageId: 21,
			},
			{
				text: "Угрево-Скатово",
				stageId: 1,
			},
			{
				text: "Рыбожирные руины",
				stageId: 15,
			},
			{
				text: "Спа-курорт «Золотая рыбка»",
				stageId: 7,
			},
			{
				text: "Микрорайон «Камбалово»",
				stageId: 12,
			},
			{
				text: "Акулий мост",
				stageId: 5,
			},
			{
				text: "«Горбуша-Маркет»",
				stageId: 10,
			},
			{
				text: "Осетровые верфи",
				stageId: 9,
			},
			{
				text: "«Манта-Мария»",
				stageId: 14,
			},
			{
				text: "Галерея «Де Берикс»",
				stageId: 6,
			},
			{
				text: "Аэропорт Пенково",
				stageId: 22,
			},
			{
				text: "Тунцовое депо",
				stageId: 20,
			},
			{
				text: "Цех «Тартар»",
				stageId: 4,
			},
			{
				text: "УсоногТорг",
				stageId: 17,
			},
			{
				text: "Крабхэттен",
				stageId: 18,
			},
			{
				text: "Приливослив",
				stageId: 3,
			},
			{
				text: "«Палтус-карго»",
				stageId: 19,
			},
			{
				text: "Академия «Лепота»",
				stageId: 8,
			},
			{
				text: "Велозал «9-й вал»",
				stageId: 16,
			},
			{
				text: "Рынок «Свисторыб»",
				stageId: 2,
			},
			{
				text: "Опаленное ущелье",
				stageId: 0,
			},
		],
	},
	{
		lang: "JPja",
		modeLabel: "ルール",
		victory: "WIN！",
		defeat: "LOSE...",
		lobbies: [
			{
				text: "Xマッチ",
				lobby: "X",
			},
			{
				text: "バンカラマッチ（チャレンジ）",
				lobby: "SERIES",
			},
			{
				text: "バンカラマッチ（オープン）",
				lobby: "OPEN",
			},
			{
				text: "プライベートマッチ",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "ナワバリバトル",
				mode: "TW",
			},
			{
				text: "ガチエリア",
				mode: "SZ",
			},
			{
				text: "ガチヤグラ",
				mode: "TC",
			},
			{
				text: "ガチホコバトル",
				mode: "RM",
			},
			{
				text: "ガチアサリ",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "リュウグウターミナル",
				stageId: 23,
			},
			{
				text: "クサヤ温泉",
				stageId: 13,
			},
			{
				text: "スメーシーワールド",
				stageId: 11,
			},
			{
				text: "デカライン高架下",
				stageId: 24,
			},
			{
				text: "バイガイ亭",
				stageId: 21,
			},
			{
				text: "ゴンズイ地区",
				stageId: 1,
			},
			{
				text: "ナンプラー遺跡",
				stageId: 15,
			},
			{
				text: "マヒマヒリゾート＆スパ",
				stageId: 7,
			},
			{
				text: "ヒラメが丘団地",
				stageId: 12,
			},
			{
				text: "マサバ海峡大橋",
				stageId: 5,
			},
			{
				text: "ザトウマーケット",
				stageId: 10,
			},
			{
				text: "チョウザメ造船",
				stageId: 9,
			},
			{
				text: "マンタマリア号",
				stageId: 14,
			},
			{
				text: "キンメダイ美術館",
				stageId: 6,
			},
			{
				text: "カジキ空港",
				stageId: 22,
			},
			{
				text: "ネギトロ炭鉱",
				stageId: 20,
			},
			{
				text: "ナメロウ金属",
				stageId: 4,
			},
			{
				text: "タラポートショッピングパーク",
				stageId: 17,
			},
			{
				text: "タカアシ経済特区",
				stageId: 18,
			},
			{
				text: "マテガイ放水路",
				stageId: 3,
			},
			{
				text: "オヒョウ海運",
				stageId: 19,
			},
			{
				text: "海女美術大学",
				stageId: 8,
			},
			{
				text: "コンブトラック",
				stageId: 16,
			},
			{
				text: "ヤガラ市場",
				stageId: 2,
			},
			{
				text: "ユノハナ大渓谷",
				stageId: 0,
			},
		],
	},
	{
		lang: "KRko",
		modeLabel: "룰",
		victory: "WIN!",
		defeat: "LOSE…",
		lobbies: [
			{
				text: "X 매치",
				lobby: "X",
			},
			{
				text: "카오폴리스 매치(챌린지)",
				lobby: "SERIES",
			},
			{
				text: "카오폴리스 매치(오픈)",
				lobby: "OPEN",
			},
			{
				text: "프라이빗 매치",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "영역 배틀",
				mode: "TW",
			},
			{
				text: "랭크 에어리어",
				mode: "SZ",
			},
			{
				text: "랭크 타워",
				mode: "TC",
			},
			{
				text: "랭크 피시 배틀",
				mode: "RM",
			},
			{
				text: "랭크 바지락",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "용궁 터미널",
				stageId: 23,
			},
			{
				text: "과메기 온천",
				stageId: 13,
			},
			{
				text: "초밥 월드",
				stageId: 11,
			},
			{
				text: "데카 라인 고가 밑",
				stageId: 24,
			},
			{
				text: "수랑정",
				stageId: 21,
			},
			{
				text: "메기 지구",
				stageId: 1,
			},
			{
				text: "남플라 유적",
				stageId: 15,
			},
			{
				text: "만새기 리조트＆스파",
				stageId: 7,
			},
			{
				text: "넙치 언덕 단지",
				stageId: 12,
			},
			{
				text: "고등어 해협 대교",
				stageId: 5,
			},
			{
				text: "혹등 마켓",
				stageId: 10,
			},
			{
				text: "철갑상어 조선소",
				stageId: 9,
			},
			{
				text: "만타 마리아호",
				stageId: 14,
			},
			{
				text: "도미 미술관",
				stageId: 6,
			},
			{
				text: "청새치 공항",
				stageId: 22,
			},
			{
				text: "참치 탄광",
				stageId: 20,
			},
			{
				text: "나메로우 금속",
				stageId: 4,
			},
			{
				text: "대구 포트 쇼핑 파크",
				stageId: 17,
			},
			{
				text: "거미게 경제특구",
				stageId: 18,
			},
			{
				text: "맛조개 방수로",
				stageId: 3,
			},
			{
				text: "광어 해운",
				stageId: 19,
			},
			{
				text: "해녀 미술 대학",
				stageId: 8,
			},
			{
				text: "다시마 트랙",
				stageId: 16,
			},
			{
				text: "대치 시장",
				stageId: 2,
			},
			{
				text: "석순 대협곡",
				stageId: 0,
			},
		],
	},
	{
		lang: "TWzh",
		modeLabel: "規則",
		victory: "WIN！",
		defeat: "LOSE……",
		lobbies: [
			{
				text: "X比賽",
				lobby: "X",
			},
			{
				text: "蠻頹比賽（挑戰）",
				lobby: "SERIES",
			},
			{
				text: "蠻頹比賽（開放）",
				lobby: "OPEN",
			},
			{
				text: "私人比賽",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "占地對戰",
				mode: "TW",
			},
			{
				text: "真格區域",
				mode: "SZ",
			},
			{
				text: "真格塔樓",
				mode: "TC",
			},
			{
				text: "真格魚虎對戰",
				mode: "RM",
			},
			{
				text: "真格蛤蜊",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "龍宮轉運站",
				stageId: 23,
			},
			{
				text: "臭魚乾溫泉",
				stageId: 13,
			},
			{
				text: "醋飯海洋世界",
				stageId: 11,
			},
			{
				text: "十路通高架橋下",
				stageId: 24,
			},
			{
				text: "貝見亭",
				stageId: 21,
			},
			{
				text: "鰻鯰區",
				stageId: 1,
			},
			{
				text: "魚露遺跡",
				stageId: 15,
			},
			{
				text: "鬼頭刀SPA度假區",
				stageId: 7,
			},
			{
				text: "比目魚住宅區",
				stageId: 12,
			},
			{
				text: "真鯖跨海大橋",
				stageId: 5,
			},
			{
				text: "座頭購物中心",
				stageId: 10,
			},
			{
				text: "鱘魚造船廠",
				stageId: 9,
			},
			{
				text: "鬼蝠魟瑪利亞號",
				stageId: 14,
			},
			{
				text: "金眼鯛美術館",
				stageId: 6,
			},
			{
				text: "旗魚機場",
				stageId: 22,
			},
			{
				text: "蔥鮪魚煤礦場",
				stageId: 20,
			},
			{
				text: "魚肉碎金屬",
				stageId: 4,
			},
			{
				text: "塔拉波特購物公園",
				stageId: 17,
			},
			{
				text: "高腳經濟特區",
				stageId: 18,
			},
			{
				text: "竹蟶疏洪道",
				stageId: 3,
			},
			{
				text: "大比目魚海運中心",
				stageId: 19,
			},
			{
				text: "海女美術大學",
				stageId: 8,
			},
			{
				text: "昆布賽道",
				stageId: 16,
			},
			{
				text: "煙管魚市場",
				stageId: 2,
			},
			{
				text: "溫泉花大峽谷",
				stageId: 0,
			},
		],
	},
	{
		lang: "USen",
		modeLabel: "Mode",
		victory: "VICTORY",
		defeat: "DEFEAT",
		lobbies: [
			{
				text: "X Battle",
				lobby: "X",
			},
			{
				text: "Anarchy Battle (Series)",
				lobby: "SERIES",
			},
			{
				text: "Anarchy Battle (Open)",
				lobby: "OPEN",
			},
			{
				text: "Private Battle",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Turf War",
				mode: "TW",
			},
			{
				text: "Splat Zones",
				mode: "SZ",
			},
			{
				text: "Tower Control",
				mode: "TC",
			},
			{
				text: "Rainmaker",
				mode: "RM",
			},
			{
				text: "Clam Blitz",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Lemuria Hub",
				stageId: 23,
			},
			{
				text: "Brinewater Springs",
				stageId: 13,
			},
			{
				text: "Wahoo World",
				stageId: 11,
			},
			{
				text: "Urchin Underpass",
				stageId: 24,
			},
			{
				text: "Robo ROM-en",
				stageId: 21,
			},
			{
				text: "Eeltail Alley",
				stageId: 1,
			},
			{
				text: "Um'ami Ruins",
				stageId: 15,
			},
			{
				text: "Mahi-Mahi Resort",
				stageId: 7,
			},
			{
				text: "Flounder Heights",
				stageId: 12,
			},
			{
				text: "Hammerhead Bridge",
				stageId: 5,
			},
			{
				text: "MakoMart",
				stageId: 10,
			},
			{
				text: "Sturgeon Shipyard",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Museum d'Alfonsino",
				stageId: 6,
			},
			{
				text: "Marlin Airport",
				stageId: 22,
			},
			{
				text: "Bluefin Depot",
				stageId: 20,
			},
			{
				text: "Mincemeat Metalworks",
				stageId: 4,
			},
			{
				text: "Barnacle & Dime",
				stageId: 17,
			},
			{
				text: "Crableg Capital",
				stageId: 18,
			},
			{
				text: "Undertow Spillway",
				stageId: 3,
			},
			{
				text: "Shipshape Cargo Co.",
				stageId: 19,
			},
			{
				text: "Inkblot Art Academy",
				stageId: 8,
			},
			{
				text: "Humpback Pump Track",
				stageId: 16,
			},
			{
				text: "Hagglefish Market",
				stageId: 2,
			},
			{
				text: "Scorch Gorge",
				stageId: 0,
			},
		],
	},
	{
		lang: "USes",
		modeLabel: "Estilo",
		victory: "¡Victoria!",
		defeat: "Derrota",
		lobbies: [
			{
				text: "Combate X",
				lobby: "X",
			},
			{
				text: "Combate caótico (formal)",
				lobby: "SERIES",
			},
			{
				text: "Combate caótico (informal)",
				lobby: "OPEN",
			},
			{
				text: "Combate privado",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Territorial",
				mode: "TW",
			},
			{
				text: "Pintazonas",
				mode: "SZ",
			},
			{
				text: "Torreón",
				mode: "TC",
			},
			{
				text: "Pez dorado",
				mode: "RM",
			},
			{
				text: "Asalto almeja",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Terminal Dragón",
				stageId: 23,
			},
			{
				text: "Balneario Aguasal",
				stageId: 13,
			},
			{
				text: "Pirañalandia",
				stageId: 11,
			},
			{
				text: "Parque Viaducto",
				stageId: 24,
			},
			{
				text: "Factoría RAMen",
				stageId: 21,
			},
			{
				text: "Callejones Crustáceo",
				stageId: 1,
			},
			{
				text: "Ruinas Ceviche",
				stageId: 15,
			},
			{
				text: "Spa Cala Bacalao",
				stageId: 7,
			},
			{
				text: "Complejo Medusa",
				stageId: 12,
			},
			{
				text: "Puente Salmón",
				stageId: 5,
			},
			{
				text: "Ultramarinos Orca",
				stageId: 10,
			},
			{
				text: "Astillero Beluga",
				stageId: 9,
			},
			{
				text: "Corbeta Corvina",
				stageId: 14,
			},
			{
				text: "Museo del Pargo",
				stageId: 6,
			},
			{
				text: "Aeropuerto Marlín",
				stageId: 22,
			},
			{
				text: "Mina costera",
				stageId: 20,
			},
			{
				text: "Desguace Mero",
				stageId: 4,
			},
			{
				text: "Unicentro Carite",
				stageId: 17,
			},
			{
				text: "Distrito Rascalópodo",
				stageId: 18,
			},
			{
				text: "Desagüe Navajuela",
				stageId: 3,
			},
			{
				text: "Carguero Platija",
				stageId: 19,
			},
			{
				text: "Instituto Coralino",
				stageId: 8,
			},
			{
				text: "Tiburódromo",
				stageId: 16,
			},
			{
				text: "Mercado Lenguado",
				stageId: 2,
			},
			{
				text: "Desfiladero Fumarola",
				stageId: 0,
			},
		],
	},
	{
		lang: "USfr",
		modeLabel: "Mode",
		victory: "Victoire!",
		defeat: "Défaite...",
		lobbies: [
			{
				text: "Match X",
				lobby: "X",
			},
			{
				text: "Match anarchie (série)",
				lobby: "SERIES",
			},
			{
				text: "Match anarchie (ouvert)",
				lobby: "OPEN",
			},
			{
				text: "Match privé",
				lobby: "PRIVATE",
			},
		],
		modes: [
			{
				text: "Guerre de territoire",
				mode: "TW",
			},
			{
				text: "Défense de zone",
				mode: "SZ",
			},
			{
				text: "Expédition risquée",
				mode: "TC",
			},
			{
				text: "Mission Bazookarpe",
				mode: "RM",
			},
			{
				text: "Pluie de palourdes",
				mode: "CB",
			},
		],
		modeWraps: [],
		stages: [
			{
				text: "Gare Aiguillat",
				stageId: 23,
			},
			{
				text: "Sources Sauret",
				stageId: 13,
			},
			{
				text: "Parc Carapince",
				stageId: 11,
			},
			{
				text: "Passage Turbot",
				stageId: 24,
			},
			{
				text: "Arène Méca-ramen",
				stageId: 21,
			},
			{
				text: "Banlieue Balibot",
				stageId: 1,
			},
			{
				text: "Ruines Uma'mi",
				stageId: 15,
			},
			{
				text: "Spa C-ta-C",
				stageId: 7,
			},
			{
				text: "Appartements Filament",
				stageId: 12,
			},
			{
				text: "Pont Esturgeon",
				stageId: 5,
			},
			{
				text: "Supermarché Cétacé",
				stageId: 10,
			},
			{
				text: "Chantier Narval",
				stageId: 9,
			},
			{
				text: "Manta Maria",
				stageId: 14,
			},
			{
				text: "Galeries Guppy",
				stageId: 6,
			},
			{
				text: "Terminal Rorqual",
				stageId: 22,
			},
			{
				text: "Mine marine",
				stageId: 20,
			},
			{
				text: "Casse Rascasse",
				stageId: 4,
			},
			{
				text: "Halles de Port-merlu",
				stageId: 17,
			},
			{
				text: "Quartier Crabe-ciels",
				stageId: 18,
			},
			{
				text: "Réservoir Rigadelle",
				stageId: 3,
			},
			{
				text: "Cargo Flétan",
				stageId: 19,
			},
			{
				text: "Institut Calm'arts",
				stageId: 8,
			},
			{
				text: "Piste Méroule",
				stageId: 16,
			},
			{
				text: "Marché Grefin",
				stageId: 2,
			},
			{
				text: "Canyon aux colonnes",
				stageId: 0,
			},
		],
	},
];
