import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";
import { introspectSchema } from "../app/db/schema-introspection.ts";
import { ensureMigratedDb } from "./ensure-test-db.ts";

const ROOT_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const TEST_DB_PATH = path.join(ROOT_DIR, "db-test.sqlite3");
const OUTPUT_PATH = path.join(ROOT_DIR, "app", "db", "schema.gen.ts");

ensureMigratedDb(TEST_DB_PATH);

const database = new DatabaseSync(TEST_DB_PATH, { readOnly: true });
const schema = introspectSchema(database);
database.close();

fs.writeFileSync(
	OUTPUT_PATH,
	`// Generated by \`pnpm run schema:generate\` from the migrated database, do not edit by hand.
// Kept in sync with the migrations by schema.gen.test.ts and with tables.ts by its type assertions.

export const SCHEMA = ${JSON.stringify(schema, null, "\t")} as const;
`,
);

execSync(`pnpm exec biome format --write ${OUTPUT_PATH}`, {
	cwd: ROOT_DIR,
	stdio: "ignore",
});

// biome-ignore lint/suspicious/noConsole: CLI script output
console.log(
	`Wrote ${Object.keys(schema).length} tables and views to ${path.relative(ROOT_DIR, OUTPUT_PATH)}`,
);
