export const LUTI_DIVS = [
	"X",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
] as const;

export const SCRIM = {
	MAX_PICKUP_SIZE_EXCLUDING_OWNER: 5,
	MAX_SAVED_PICKUP_ROSTERS: 5,
	PICKUP_ROSTER_EXPIRES_IN_MONTHS: 3,
	MIN_MEMBERS_PER_TEAM: 4,
	CANCEL_REASON_MAX_LENGTH: 500,
	REQUEST_MESSAGE_MAX_LENGTH: 200,
	MAX_TIME_RANGE_MS: 3 * 60 * 60 * 1000, // 3 hours
	AUTO_CANCEL_WINDOW_HOURS: 1,
};

export const SCRIM_TRACKING_AUTO_LOCK_HOURS = 4;
