/**
 * GENERATED by tools/build-localized-entries.ts from the splat3 repo's
 * language dumps — do not edit by hand; regenerate when the game adds
 * content. Localized versus-UI strings for every game language,
 * each mapped to its canonical English value (src/core/localized.ts
 * derives the flattened match sets detectors snap OCR output against).
 */

export interface LocalizedText {
  text: string;
  /** the canonical English value events report */
  canonical: string;
}

export interface LanguageEntries {
  lang: string;
  /** the intro splash's constant "MODE" label */
  modeLabel: string;
  /** replay-browser winner/loser panel tags */
  victory: string;
  defeat: string;
  lobbies: LocalizedText[];
  modes: LocalizedText[];
  /** two-line intro-splash wrap variants ("Muschel-\nchaos"), space-joined */
  modeWraps: LocalizedText[];
  stages: LocalizedText[];
}

export const LANGUAGE_ENTRIES: readonly LanguageEntries[] = [
  {
    lang: "CNzh",
    modeLabel: "规则",
    victory: "WIN！",
    defeat: "LOSE...",
    lobbies: [
      {
        text: "X比赛",
        canonical: "X Battle",
      },
      {
        text: "蛮颓比赛（挑战）",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "蛮颓比赛（开放）",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "私人比赛",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "占地对战",
        canonical: "Turf War",
      },
      {
        text: "真格区域",
        canonical: "Splat Zones",
      },
      {
        text: "真格塔楼",
        canonical: "Tower Control",
      },
      {
        text: "真格鱼虎对战",
        canonical: "Rainmaker",
      },
      {
        text: "真格蛤蜊",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "龙宫转运站",
        canonical: "Lemuria Hub",
      },
      {
        text: "臭鱼干温泉",
        canonical: "Brinewater Springs",
      },
      {
        text: "醋饭海洋世界",
        canonical: "Wahoo World",
      },
      {
        text: "十路通高架桥下",
        canonical: "Urchin Underpass",
      },
      {
        text: "贝见亭",
        canonical: "Robo ROM-en",
      },
      {
        text: "鳗鲶区",
        canonical: "Eeltail Alley",
      },
      {
        text: "鱼露遗迹",
        canonical: "Um'ami Ruins",
      },
      {
        text: "鬼头刀SPA度假区",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "比目鱼住宅区",
        canonical: "Flounder Heights",
      },
      {
        text: "真鲭跨海大桥",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "座头购物中心",
        canonical: "MakoMart",
      },
      {
        text: "鲟鱼造船厂",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "鬼蝠鲼玛利亚号",
        canonical: "Manta Maria",
      },
      {
        text: "金眼鲷美术馆",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "旗鱼机场",
        canonical: "Marlin Airport",
      },
      {
        text: "葱鲔鱼煤矿场",
        canonical: "Bluefin Depot",
      },
      {
        text: "鱼肉碎金属",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "塔拉波特购物公园",
        canonical: "Barnacle & Dime",
      },
      {
        text: "高脚经济特区",
        canonical: "Crableg Capital",
      },
      {
        text: "竹蛏疏洪道",
        canonical: "Undertow Spillway",
      },
      {
        text: "大比目鱼海运中心",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "海女美术大学",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "昆布赛道",
        canonical: "Humpback Pump Track",
      },
      {
        text: "烟管鱼市场",
        canonical: "Hagglefish Market",
      },
      {
        text: "温泉花大峡谷",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUde",
    modeLabel: "Kampfart",
    victory: "Sieg!",
    defeat: "Verloren...",
    lobbies: [
      {
        text: "X-Kampf",
        canonical: "X Battle",
      },
      {
        text: "Anarchie-Kampf (Serie)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Anarchie-Kampf (Offen)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Privater Kampf",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Revierkampf",
        canonical: "Turf War",
      },
      {
        text: "Herrschaft",
        canonical: "Splat Zones",
      },
      {
        text: "Turm-Kommando",
        canonical: "Tower Control",
      },
      {
        text: "Operation Goldfisch",
        canonical: "Rainmaker",
      },
      {
        text: "Muschelchaos",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [
      {
        text: "Revier- kampf",
        canonical: "Turf War",
      },
      {
        text: "Muschel- chaos",
        canonical: "Clam Blitz",
      },
    ],
    stages: [
      {
        text: "Bahnhof Lemuria",
        canonical: "Lemuria Hub",
      },
      {
        text: "Kusaya-Quellen",
        canonical: "Brinewater Springs",
      },
      {
        text: "Flunder-Funpark",
        canonical: "Wahoo World",
      },
      {
        text: "Dekabahnstation",
        canonical: "Urchin Underpass",
      },
      {
        text: "ROM & RAMen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Streifenaal-Straße",
        canonical: "Eeltail Alley",
      },
      {
        text: "Um'ami-Ruinen",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Mahi-Mahi-Resort",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Schollensiedlung",
        canonical: "Flounder Heights",
      },
      {
        text: "Makrelenbrücke",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Cetacea-Markt",
        canonical: "MakoMart",
      },
      {
        text: "Störwerft",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Pinakoithek",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "La Ola Airport",
        canonical: "Marlin Airport",
      },
      {
        text: "Blauflossen-Depot",
        canonical: "Bluefin Depot",
      },
      {
        text: "Aalstahl-Metallwerk",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Talerfisch & Pock",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Seespinnen-Skyline",
        canonical: "Crableg Capital",
      },
      {
        text: "Schwertmuschel-Reservoir",
        canonical: "Undertow Spillway",
      },
      {
        text: "Frachtschiff Schwerfisch",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Perlmutt-Akademie",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Buckelwal-Piste",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Schnapperchen-Basar",
        canonical: "Hagglefish Market",
      },
      {
        text: "Sengkluft",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUen",
    modeLabel: "Mode",
    victory: "VICTORY",
    defeat: "DEFEAT",
    lobbies: [
      {
        text: "X Battle",
        canonical: "X Battle",
      },
      {
        text: "Anarchy Battle (Series)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Anarchy Battle (Open)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Private Battle",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Turf War",
        canonical: "Turf War",
      },
      {
        text: "Splat Zones",
        canonical: "Splat Zones",
      },
      {
        text: "Tower Control",
        canonical: "Tower Control",
      },
      {
        text: "Rainmaker",
        canonical: "Rainmaker",
      },
      {
        text: "Clam Blitz",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Lemuria Hub",
        canonical: "Lemuria Hub",
      },
      {
        text: "Brinewater Springs",
        canonical: "Brinewater Springs",
      },
      {
        text: "Wahoo World",
        canonical: "Wahoo World",
      },
      {
        text: "Urchin Underpass",
        canonical: "Urchin Underpass",
      },
      {
        text: "Robo ROM-en",
        canonical: "Robo ROM-en",
      },
      {
        text: "Eeltail Alley",
        canonical: "Eeltail Alley",
      },
      {
        text: "Um'ami Ruins",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Mahi-Mahi Resort",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Flounder Heights",
        canonical: "Flounder Heights",
      },
      {
        text: "Hammerhead Bridge",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "MakoMart",
        canonical: "MakoMart",
      },
      {
        text: "Sturgeon Shipyard",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Museum d'Alfonsino",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Marlin Airport",
        canonical: "Marlin Airport",
      },
      {
        text: "Bluefin Depot",
        canonical: "Bluefin Depot",
      },
      {
        text: "Mincemeat Metalworks",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Barnacle & Dime",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Crableg Capital",
        canonical: "Crableg Capital",
      },
      {
        text: "Undertow Spillway",
        canonical: "Undertow Spillway",
      },
      {
        text: "Shipshape Cargo Co.",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Inkblot Art Academy",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Humpback Pump Track",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Hagglefish Market",
        canonical: "Hagglefish Market",
      },
      {
        text: "Scorch Gorge",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUes",
    modeLabel: "Estilo",
    victory: "¡Victoria!",
    defeat: "Derrota",
    lobbies: [
      {
        text: "Combate X",
        canonical: "X Battle",
      },
      {
        text: "Combate caótico (formal)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Combate caótico (informal)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Combate privado",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Territorial",
        canonical: "Turf War",
      },
      {
        text: "Pintazonas",
        canonical: "Splat Zones",
      },
      {
        text: "Torre",
        canonical: "Tower Control",
      },
      {
        text: "Pez dorado",
        canonical: "Rainmaker",
      },
      {
        text: "Asalto almeja",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [
      {
        text: "Terri- torial",
        canonical: "Turf War",
      },
      {
        text: "Pinta- zonas",
        canonical: "Splat Zones",
      },
    ],
    stages: [
      {
        text: "Terminal Dragón",
        canonical: "Lemuria Hub",
      },
      {
        text: "Balneario Aguasal",
        canonical: "Brinewater Springs",
      },
      {
        text: "Pirañalandia",
        canonical: "Wahoo World",
      },
      {
        text: "Parque Viaducto",
        canonical: "Urchin Underpass",
      },
      {
        text: "Factoría RAMen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Callejones Crustáceo",
        canonical: "Eeltail Alley",
      },
      {
        text: "Ruinas Ceviche",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Spa Cala Bacalao",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Complejo Medusa",
        canonical: "Flounder Heights",
      },
      {
        text: "Puente Salmón",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Ultramarinos Orca",
        canonical: "MakoMart",
      },
      {
        text: "Astillero Beluga",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Corbeta Corvina",
        canonical: "Manta Maria",
      },
      {
        text: "Museo del Pargo",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Aeropuerto Marlín",
        canonical: "Marlin Airport",
      },
      {
        text: "Mina costera",
        canonical: "Bluefin Depot",
      },
      {
        text: "Desguace Mero",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Centro Comercial Fletán",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Distrito Rascalópodo",
        canonical: "Crableg Capital",
      },
      {
        text: "Cisterna Navajuela",
        canonical: "Undertow Spillway",
      },
      {
        text: "Carguero Platija",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Instituto Coralino",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Tiburódromo",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Mercado Lenguado",
        canonical: "Hagglefish Market",
      },
      {
        text: "Desfiladero Fumarola",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUfr",
    modeLabel: "Mode",
    victory: "Victoire !",
    defeat: "Défaite...",
    lobbies: [
      {
        text: "Match X",
        canonical: "X Battle",
      },
      {
        text: "Match anarchie (série)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Match anarchie (ouvert)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Match privé",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Guerre de territoire",
        canonical: "Turf War",
      },
      {
        text: "Défense de zone",
        canonical: "Splat Zones",
      },
      {
        text: "Expédition risquée",
        canonical: "Tower Control",
      },
      {
        text: "Mission Bazookarpe",
        canonical: "Rainmaker",
      },
      {
        text: "Pluie de palourdes",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Gare Aiguillat",
        canonical: "Lemuria Hub",
      },
      {
        text: "Sources Sauret",
        canonical: "Brinewater Springs",
      },
      {
        text: "Parc Carapince",
        canonical: "Wahoo World",
      },
      {
        text: "Passage Turbot",
        canonical: "Urchin Underpass",
      },
      {
        text: "Arène Méca-ramen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Banlieue Balibot",
        canonical: "Eeltail Alley",
      },
      {
        text: "Ruines Uma'mi",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Club Ca$halot",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Lotissement Filament",
        canonical: "Flounder Heights",
      },
      {
        text: "Pont Esturgeon",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Supermarché Cétacé",
        canonical: "MakoMart",
      },
      {
        text: "Chantier Narval",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Galeries Guppy",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Terminal Rorqual",
        canonical: "Marlin Airport",
      },
      {
        text: "Mine marine",
        canonical: "Bluefin Depot",
      },
      {
        text: "Casse Rascasse",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Halles de Port-merlu",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Quartier Crabe-ciels",
        canonical: "Crableg Capital",
      },
      {
        text: "Réservoir Rigadelle",
        canonical: "Undertow Spillway",
      },
      {
        text: "Chaland Flétan",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Institut Calam'arts",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Piste Méroule",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Marché Grefin",
        canonical: "Hagglefish Market",
      },
      {
        text: "Canyon aux colonnes",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUit",
    modeLabel: "Modalità",
    victory: "Vittoria",
    defeat: "Sconfitta",
    lobbies: [
      {
        text: "Partita X",
        canonical: "X Battle",
      },
      {
        text: "Partita anarchica (Serie)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Partita anarchica (Aperta)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Partita privata",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Mischia mollusca",
        canonical: "Turf War",
      },
      {
        text: "Zona splat",
        canonical: "Splat Zones",
      },
      {
        text: "Torre mobile",
        canonical: "Tower Control",
      },
      {
        text: "Bazookarp",
        canonical: "Rainmaker",
      },
      {
        text: "Vongol gol",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Stazione Lemuria",
        canonical: "Lemuria Hub",
      },
      {
        text: "Fermenterme",
        canonical: "Brinewater Springs",
      },
      {
        text: "Soglioland",
        canonical: "Wahoo World",
      },
      {
        text: "Periferia urbana",
        canonical: "Urchin Underpass",
      },
      {
        text: "Roboramen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Sobborgo Siluriano",
        canonical: "Eeltail Alley",
      },
      {
        text: "Rovine Salsadipesce",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Villanguilla",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Cime Sogliolose",
        canonical: "Flounder Heights",
      },
      {
        text: "Ponte Sgombro",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Mercatotano",
        canonical: "MakoMart",
      },
      {
        text: "Cantiere Pinnenere",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Museo di Cefalò",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Aeroporto Ondabianca",
        canonical: "Marlin Airport",
      },
      {
        text: "Molo Mollusco",
        canonical: "Bluefin Depot",
      },
      {
        text: "Discarica Tritatutto",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Empolporio",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Granchiacieli",
        canonical: "Crableg Capital",
      },
      {
        text: "Cisterna Cernia",
        canonical: "Undertow Spillway",
      },
      {
        text: "Platessa Trasporti S.r.l.",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Campus Hippocampus",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Tintodromo Montecarpa",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Mercato Fruttato",
        canonical: "Hagglefish Market",
      },
      {
        text: "Grank Canyon",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUnl",
    modeLabel: "Vechtstijl",
    victory: "Gewonnen!",
    defeat: "Verloren...",
    lobbies: [
      {
        text: "X-gevecht",
        canonical: "X Battle",
      },
      {
        text: "Chaosgevecht (sessie)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Chaosgevecht (open)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Privégevecht",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Grondoorlog",
        canonical: "Turf War",
      },
      {
        text: "Spetterzone",
        canonical: "Splat Zones",
      },
      {
        text: "Torentwist",
        canonical: "Tower Control",
      },
      {
        text: "Bazookarper",
        canonical: "Rainmaker",
      },
      {
        text: "Schelpenstrijd",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [
      {
        text: "Grond- oorlog",
        canonical: "Turf War",
      },
      {
        text: "Spetter- zone",
        canonical: "Splat Zones",
      },
      {
        text: "Toren- twist",
        canonical: "Tower Control",
      },
      {
        text: "Bazoo- karper",
        canonical: "Rainmaker",
      },
      {
        text: "Schelpen- strijd",
        canonical: "Clam Blitz",
      },
    ],
    stages: [
      {
        text: "Lemurië Centraal",
        canonical: "Lemuria Hub",
      },
      {
        text: "Barbeelbaden",
        canonical: "Brinewater Springs",
      },
      {
        text: "Waterwonderland",
        canonical: "Wahoo World",
      },
      {
        text: "Knooppunt Kabeljauw",
        canonical: "Urchin Underpass",
      },
      {
        text: "Bami-Byte",
        canonical: "Robo ROM-en",
      },
      {
        text: "Forelviaduct",
        canonical: "Eeltail Alley",
      },
      {
        text: "Ruisvoornruïnes",
        canonical: "Um'ami Ruins",
      },
      {
        text: "El Dorade-resort",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Baleinbuurt",
        canonical: "Flounder Heights",
      },
      {
        text: "Brandingbrug",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Bultrugbazaar",
        canonical: "MakoMart",
      },
      {
        text: "Walruswerf",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Klipvisklipper",
        canonical: "Manta Maria",
      },
      {
        text: "Galerie Le Guppy",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Trekvis Airport",
        canonical: "Marlin Airport",
      },
      {
        text: "Blauwvin-depot",
        canonical: "Bluefin Depot",
      },
      {
        text: "Zilversmelt-hoogovens",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Winkelcentrum Poon & Zeehaan",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Visstickdistrict",
        canonical: "Crableg Capital",
      },
      {
        text: "Baarsreservoir",
        canonical: "Undertow Spillway",
      },
      {
        text: "Tarbot Transport",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Koraalcampus",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Lekkerbektrack",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Boter-bij-de-vismarkt",
        canonical: "Hagglefish Market",
      },
      {
        text: "Roggentrog",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "EUru",
    modeLabel: "Режим",
    victory: "Успех!",
    defeat: "Провал",
    lobbies: [
      {
        text: "Бой X",
        canonical: "X Battle",
      },
      {
        text: "Стихийный бой (серия)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Стихийный бой (открытый)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Частный бой",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Бой за район",
        canonical: "Turf War",
      },
      {
        text: "Бой за зоны",
        canonical: "Splat Zones",
      },
      {
        text: "Бой за башню",
        canonical: "Tower Control",
      },
      {
        text: "Мегакарп",
        canonical: "Rainmaker",
      },
      {
        text: "Устробол",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [
      {
        text: "Устро- бол",
        canonical: "Clam Blitz",
      },
    ],
    stages: [
      {
        text: "Вокзал Лемурия",
        canonical: "Lemuria Hub",
      },
      {
        text: "Тухловодск",
        canonical: "Brinewater Springs",
      },
      {
        text: "Луна-парк «Язь»",
        canonical: "Wahoo World",
      },
      {
        text: "Район Дека",
        canonical: "Urchin Underpass",
      },
      {
        text: "«Роборамэн»",
        canonical: "Robo ROM-en",
      },
      {
        text: "Угрево-Скатово",
        canonical: "Eeltail Alley",
      },
      {
        text: "Рыбожирные руины",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Спа-курорт «Золотая рыбка»",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Микрорайон «Камбалово»",
        canonical: "Flounder Heights",
      },
      {
        text: "Акулий мост",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "«Горбуша-Маркет»",
        canonical: "MakoMart",
      },
      {
        text: "Осетровые верфи",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "«Манта-Мария»",
        canonical: "Manta Maria",
      },
      {
        text: "Галерея «Де Берикс»",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Аэропорт Пенково",
        canonical: "Marlin Airport",
      },
      {
        text: "Тунцовое депо",
        canonical: "Bluefin Depot",
      },
      {
        text: "Цех «Тартар»",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "УсоногТорг",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Крабхэттен",
        canonical: "Crableg Capital",
      },
      {
        text: "Приливослив",
        canonical: "Undertow Spillway",
      },
      {
        text: "«Палтус-карго»",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Академия «Лепота»",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Велозал «9-й вал»",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Рынок «Свисторыб»",
        canonical: "Hagglefish Market",
      },
      {
        text: "Опаленное ущелье",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "JPja",
    modeLabel: "ルール",
    victory: "WIN！",
    defeat: "LOSE...",
    lobbies: [
      {
        text: "Xマッチ",
        canonical: "X Battle",
      },
      {
        text: "バンカラマッチ（チャレンジ）",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "バンカラマッチ（オープン）",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "プライベートマッチ",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "ナワバリバトル",
        canonical: "Turf War",
      },
      {
        text: "ガチエリア",
        canonical: "Splat Zones",
      },
      {
        text: "ガチヤグラ",
        canonical: "Tower Control",
      },
      {
        text: "ガチホコバトル",
        canonical: "Rainmaker",
      },
      {
        text: "ガチアサリ",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "リュウグウターミナル",
        canonical: "Lemuria Hub",
      },
      {
        text: "クサヤ温泉",
        canonical: "Brinewater Springs",
      },
      {
        text: "スメーシーワールド",
        canonical: "Wahoo World",
      },
      {
        text: "デカライン高架下",
        canonical: "Urchin Underpass",
      },
      {
        text: "バイガイ亭",
        canonical: "Robo ROM-en",
      },
      {
        text: "ゴンズイ地区",
        canonical: "Eeltail Alley",
      },
      {
        text: "ナンプラー遺跡",
        canonical: "Um'ami Ruins",
      },
      {
        text: "マヒマヒリゾート＆スパ",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "ヒラメが丘団地",
        canonical: "Flounder Heights",
      },
      {
        text: "マサバ海峡大橋",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "ザトウマーケット",
        canonical: "MakoMart",
      },
      {
        text: "チョウザメ造船",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "マンタマリア号",
        canonical: "Manta Maria",
      },
      {
        text: "キンメダイ美術館",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "カジキ空港",
        canonical: "Marlin Airport",
      },
      {
        text: "ネギトロ炭鉱",
        canonical: "Bluefin Depot",
      },
      {
        text: "ナメロウ金属",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "タラポートショッピングパーク",
        canonical: "Barnacle & Dime",
      },
      {
        text: "タカアシ経済特区",
        canonical: "Crableg Capital",
      },
      {
        text: "マテガイ放水路",
        canonical: "Undertow Spillway",
      },
      {
        text: "オヒョウ海運",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "海女美術大学",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "コンブトラック",
        canonical: "Humpback Pump Track",
      },
      {
        text: "ヤガラ市場",
        canonical: "Hagglefish Market",
      },
      {
        text: "ユノハナ大渓谷",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "KRko",
    modeLabel: "룰",
    victory: "WIN!",
    defeat: "LOSE…",
    lobbies: [
      {
        text: "X 매치",
        canonical: "X Battle",
      },
      {
        text: "카오폴리스 매치(챌린지)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "카오폴리스 매치(오픈)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "프라이빗 매치",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "영역 배틀",
        canonical: "Turf War",
      },
      {
        text: "랭크 에어리어",
        canonical: "Splat Zones",
      },
      {
        text: "랭크 타워",
        canonical: "Tower Control",
      },
      {
        text: "랭크 피시 배틀",
        canonical: "Rainmaker",
      },
      {
        text: "랭크 바지락",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "용궁 터미널",
        canonical: "Lemuria Hub",
      },
      {
        text: "과메기 온천",
        canonical: "Brinewater Springs",
      },
      {
        text: "초밥 월드",
        canonical: "Wahoo World",
      },
      {
        text: "데카 라인 고가 밑",
        canonical: "Urchin Underpass",
      },
      {
        text: "수랑정",
        canonical: "Robo ROM-en",
      },
      {
        text: "메기 지구",
        canonical: "Eeltail Alley",
      },
      {
        text: "남플라 유적",
        canonical: "Um'ami Ruins",
      },
      {
        text: "만새기 리조트＆스파",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "넙치 언덕 단지",
        canonical: "Flounder Heights",
      },
      {
        text: "고등어 해협 대교",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "혹등 마켓",
        canonical: "MakoMart",
      },
      {
        text: "철갑상어 조선소",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "만타 마리아호",
        canonical: "Manta Maria",
      },
      {
        text: "도미 미술관",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "청새치 공항",
        canonical: "Marlin Airport",
      },
      {
        text: "참치 탄광",
        canonical: "Bluefin Depot",
      },
      {
        text: "나메로우 금속",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "대구 포트 쇼핑 파크",
        canonical: "Barnacle & Dime",
      },
      {
        text: "거미게 경제특구",
        canonical: "Crableg Capital",
      },
      {
        text: "맛조개 방수로",
        canonical: "Undertow Spillway",
      },
      {
        text: "광어 해운",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "해녀 미술 대학",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "다시마 트랙",
        canonical: "Humpback Pump Track",
      },
      {
        text: "대치 시장",
        canonical: "Hagglefish Market",
      },
      {
        text: "석순 대협곡",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "TWzh",
    modeLabel: "規則",
    victory: "WIN！",
    defeat: "LOSE……",
    lobbies: [
      {
        text: "X比賽",
        canonical: "X Battle",
      },
      {
        text: "蠻頹比賽（挑戰）",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "蠻頹比賽（開放）",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "私人比賽",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "占地對戰",
        canonical: "Turf War",
      },
      {
        text: "真格區域",
        canonical: "Splat Zones",
      },
      {
        text: "真格塔樓",
        canonical: "Tower Control",
      },
      {
        text: "真格魚虎對戰",
        canonical: "Rainmaker",
      },
      {
        text: "真格蛤蜊",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "龍宮轉運站",
        canonical: "Lemuria Hub",
      },
      {
        text: "臭魚乾溫泉",
        canonical: "Brinewater Springs",
      },
      {
        text: "醋飯海洋世界",
        canonical: "Wahoo World",
      },
      {
        text: "十路通高架橋下",
        canonical: "Urchin Underpass",
      },
      {
        text: "貝見亭",
        canonical: "Robo ROM-en",
      },
      {
        text: "鰻鯰區",
        canonical: "Eeltail Alley",
      },
      {
        text: "魚露遺跡",
        canonical: "Um'ami Ruins",
      },
      {
        text: "鬼頭刀SPA度假區",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "比目魚住宅區",
        canonical: "Flounder Heights",
      },
      {
        text: "真鯖跨海大橋",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "座頭購物中心",
        canonical: "MakoMart",
      },
      {
        text: "鱘魚造船廠",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "鬼蝠魟瑪利亞號",
        canonical: "Manta Maria",
      },
      {
        text: "金眼鯛美術館",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "旗魚機場",
        canonical: "Marlin Airport",
      },
      {
        text: "蔥鮪魚煤礦場",
        canonical: "Bluefin Depot",
      },
      {
        text: "魚肉碎金屬",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "塔拉波特購物公園",
        canonical: "Barnacle & Dime",
      },
      {
        text: "高腳經濟特區",
        canonical: "Crableg Capital",
      },
      {
        text: "竹蟶疏洪道",
        canonical: "Undertow Spillway",
      },
      {
        text: "大比目魚海運中心",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "海女美術大學",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "昆布賽道",
        canonical: "Humpback Pump Track",
      },
      {
        text: "煙管魚市場",
        canonical: "Hagglefish Market",
      },
      {
        text: "溫泉花大峽谷",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "USen",
    modeLabel: "Mode",
    victory: "VICTORY",
    defeat: "DEFEAT",
    lobbies: [
      {
        text: "X Battle",
        canonical: "X Battle",
      },
      {
        text: "Anarchy Battle (Series)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Anarchy Battle (Open)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Private Battle",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Turf War",
        canonical: "Turf War",
      },
      {
        text: "Splat Zones",
        canonical: "Splat Zones",
      },
      {
        text: "Tower Control",
        canonical: "Tower Control",
      },
      {
        text: "Rainmaker",
        canonical: "Rainmaker",
      },
      {
        text: "Clam Blitz",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Lemuria Hub",
        canonical: "Lemuria Hub",
      },
      {
        text: "Brinewater Springs",
        canonical: "Brinewater Springs",
      },
      {
        text: "Wahoo World",
        canonical: "Wahoo World",
      },
      {
        text: "Urchin Underpass",
        canonical: "Urchin Underpass",
      },
      {
        text: "Robo ROM-en",
        canonical: "Robo ROM-en",
      },
      {
        text: "Eeltail Alley",
        canonical: "Eeltail Alley",
      },
      {
        text: "Um'ami Ruins",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Mahi-Mahi Resort",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Flounder Heights",
        canonical: "Flounder Heights",
      },
      {
        text: "Hammerhead Bridge",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "MakoMart",
        canonical: "MakoMart",
      },
      {
        text: "Sturgeon Shipyard",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Museum d'Alfonsino",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Marlin Airport",
        canonical: "Marlin Airport",
      },
      {
        text: "Bluefin Depot",
        canonical: "Bluefin Depot",
      },
      {
        text: "Mincemeat Metalworks",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Barnacle & Dime",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Crableg Capital",
        canonical: "Crableg Capital",
      },
      {
        text: "Undertow Spillway",
        canonical: "Undertow Spillway",
      },
      {
        text: "Shipshape Cargo Co.",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Inkblot Art Academy",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Humpback Pump Track",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Hagglefish Market",
        canonical: "Hagglefish Market",
      },
      {
        text: "Scorch Gorge",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "USes",
    modeLabel: "Estilo",
    victory: "¡Victoria!",
    defeat: "Derrota",
    lobbies: [
      {
        text: "Combate X",
        canonical: "X Battle",
      },
      {
        text: "Combate caótico (formal)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Combate caótico (informal)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Combate privado",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Territorial",
        canonical: "Turf War",
      },
      {
        text: "Pintazonas",
        canonical: "Splat Zones",
      },
      {
        text: "Torreón",
        canonical: "Tower Control",
      },
      {
        text: "Pez dorado",
        canonical: "Rainmaker",
      },
      {
        text: "Asalto almeja",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Terminal Dragón",
        canonical: "Lemuria Hub",
      },
      {
        text: "Balneario Aguasal",
        canonical: "Brinewater Springs",
      },
      {
        text: "Pirañalandia",
        canonical: "Wahoo World",
      },
      {
        text: "Parque Viaducto",
        canonical: "Urchin Underpass",
      },
      {
        text: "Factoría RAMen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Callejones Crustáceo",
        canonical: "Eeltail Alley",
      },
      {
        text: "Ruinas Ceviche",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Spa Cala Bacalao",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Complejo Medusa",
        canonical: "Flounder Heights",
      },
      {
        text: "Puente Salmón",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Ultramarinos Orca",
        canonical: "MakoMart",
      },
      {
        text: "Astillero Beluga",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Corbeta Corvina",
        canonical: "Manta Maria",
      },
      {
        text: "Museo del Pargo",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Aeropuerto Marlín",
        canonical: "Marlin Airport",
      },
      {
        text: "Mina costera",
        canonical: "Bluefin Depot",
      },
      {
        text: "Desguace Mero",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Unicentro Carite",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Distrito Rascalópodo",
        canonical: "Crableg Capital",
      },
      {
        text: "Desagüe Navajuela",
        canonical: "Undertow Spillway",
      },
      {
        text: "Carguero Platija",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Instituto Coralino",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Tiburódromo",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Mercado Lenguado",
        canonical: "Hagglefish Market",
      },
      {
        text: "Desfiladero Fumarola",
        canonical: "Scorch Gorge",
      },
    ],
  },
  {
    lang: "USfr",
    modeLabel: "Mode",
    victory: "Victoire!",
    defeat: "Défaite...",
    lobbies: [
      {
        text: "Match X",
        canonical: "X Battle",
      },
      {
        text: "Match anarchie (série)",
        canonical: "Anarchy Battle (Series)",
      },
      {
        text: "Match anarchie (ouvert)",
        canonical: "Anarchy Battle (Open)",
      },
      {
        text: "Match privé",
        canonical: "Private Battle",
      },
    ],
    modes: [
      {
        text: "Guerre de territoire",
        canonical: "Turf War",
      },
      {
        text: "Défense de zone",
        canonical: "Splat Zones",
      },
      {
        text: "Expédition risquée",
        canonical: "Tower Control",
      },
      {
        text: "Mission Bazookarpe",
        canonical: "Rainmaker",
      },
      {
        text: "Pluie de palourdes",
        canonical: "Clam Blitz",
      },
    ],
    modeWraps: [],
    stages: [
      {
        text: "Gare Aiguillat",
        canonical: "Lemuria Hub",
      },
      {
        text: "Sources Sauret",
        canonical: "Brinewater Springs",
      },
      {
        text: "Parc Carapince",
        canonical: "Wahoo World",
      },
      {
        text: "Passage Turbot",
        canonical: "Urchin Underpass",
      },
      {
        text: "Arène Méca-ramen",
        canonical: "Robo ROM-en",
      },
      {
        text: "Banlieue Balibot",
        canonical: "Eeltail Alley",
      },
      {
        text: "Ruines Uma'mi",
        canonical: "Um'ami Ruins",
      },
      {
        text: "Spa C-ta-C",
        canonical: "Mahi-Mahi Resort",
      },
      {
        text: "Appartements Filament",
        canonical: "Flounder Heights",
      },
      {
        text: "Pont Esturgeon",
        canonical: "Hammerhead Bridge",
      },
      {
        text: "Supermarché Cétacé",
        canonical: "MakoMart",
      },
      {
        text: "Chantier Narval",
        canonical: "Sturgeon Shipyard",
      },
      {
        text: "Manta Maria",
        canonical: "Manta Maria",
      },
      {
        text: "Galeries Guppy",
        canonical: "Museum d'Alfonsino",
      },
      {
        text: "Terminal Rorqual",
        canonical: "Marlin Airport",
      },
      {
        text: "Mine marine",
        canonical: "Bluefin Depot",
      },
      {
        text: "Casse Rascasse",
        canonical: "Mincemeat Metalworks",
      },
      {
        text: "Halles de Port-merlu",
        canonical: "Barnacle & Dime",
      },
      {
        text: "Quartier Crabe-ciels",
        canonical: "Crableg Capital",
      },
      {
        text: "Réservoir Rigadelle",
        canonical: "Undertow Spillway",
      },
      {
        text: "Cargo Flétan",
        canonical: "Shipshape Cargo Co.",
      },
      {
        text: "Institut Calm'arts",
        canonical: "Inkblot Art Academy",
      },
      {
        text: "Piste Méroule",
        canonical: "Humpback Pump Track",
      },
      {
        text: "Marché Grefin",
        canonical: "Hagglefish Market",
      },
      {
        text: "Canyon aux colonnes",
        canonical: "Scorch Gorge",
      },
    ],
  },
];
