export const TROPHY_NAME_MIN_LENGTH = 1;
export const TROPHY_NAME_MAX_LENGTH = 32;

export const TROPHY_MODEL_MAX_LENGTH = 1024 * 1024;

export const TROPHY_DESCRIPTION_MAX_LENGTH = 3000;

export const TROPHY_DECLINE_REASON_MIN_LENGTH = 1;
export const TROPHY_DECLINE_REASON_MAX_LENGTH = 3000;
